name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ 授予写入权限
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 关键配置
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的 token
          publish_dir: ./_site
          publish_branch: gh-pages  # 目标分支
          force_orphan: true  # 强制清空历史（适用于首次部署）
          keep_files: false   # 不保留旧文件
